name: Sync with Upstream

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/5etools-mirror-3/5etools-src.git
    
    - name: Fetch upstream
      run: git fetch upstream
    
    - name: Merge upstream changes
      run: git merge upstream/main --no-edit
    
    - name: Clone images repository
      run: |
        git clone https://github.com/DaffyRoth/5etools-img.git temp-img
        rm -rf img
        mv temp-img img
        rm -rf img/.git
    
    - name: Commit images if changed
      run: |
        git add img/
        git diff --staged --quiet || git commit -m "Update images from 5etools-img repository"
    
    - name: Push changes
      run: git push origin main
